### ISSUE TITLE
New Radar System

### ISSUE THREAD

**Issue by NikolaiVChr** [NikolaiVChr/f16#390]
**Bugs**
* #376 
* [ ] DLINK symbol on non-dlink aircraft. Same MP person (but had switched aircraft to ATC)
* [ ] MFD OBS colors on b50
* 

**Todo**
* [ ] Deploy
* [ ] GM tilt angles (needs serious thinking)
* [ ] Clicking A-G should set GM
* [ ] VSR switch speed at each bar instead of each frame

**Comment by NikolaiVChr** [comment]
To test the new radar, checkout branch `radarSystem`.

**Comment by NikolaiVChr** [comment]
Some random info:

**BARS and AZ**
![image](https://user-images.githubusercontent.com/3764194/146894375-9a009b34-dd60-49c4-8003-757af64e4e05.png)
Imagine you are using 4 bars
Thats the **D** on the picture
But you are flying low and want to scan higher
The the antennae knob (key `i` and `I`) can lift the entire 4 bar scan pattern up
The pattern is normally centered on the horizon, even if you pitch up (to certain degree)
The old radar would scan instantly the entire 60 deg up/down coverage.
But unless the target you want to scan is very close, most of the time you don't even need 4 bars or full azimuth sideways coverage of +/- 60 degs.
2 bars with 30 degs sideways coverage is often enough.
With the cursor you can move the sideways coverage (when you are not in full 60 degs mode [ which is called A6 on the display])

So 4 bars will scan double as much (vertically) than 2 bars. But 2 bars scans faster, because the disc don't have to move through all 4 bars, only 2.

So in the picture below, I have set it to A2 (which is 20+ deg to each side of the cursor).
3B which is 3 bars.
Where the cursor is, the coverage is -8000ft to 17000ft. That's indicated right of the cursor.
The mode is TWS (track while scan), which can show headings of multiple targets at once. But that mode require 2 scans per target to get the heading. And has max of 80nm.

Click CRM to switch master mode.
Click TWS to switch mode.

![image](https://user-images.githubusercontent.com/3764194/146894725-bd08181d-e877-4cd8-96ef-d9003931432a.png)

In the above picture notice the 2 `T` one at bottom and one at left side. Those represent the radar disc movement, sideways and up/down.

**CLUTTER**
I have removed the groundclutter background rendering (for now at least). Once I figure out smart way to remake it, I will. But problem is some peoples PCs is not strong enough to have it on.
For moving groundtargets, there is now a special mode (GMT) just for them, so its piece of cake to lock them up, sorry.
For static ground targets it sorta works like before. I have yet to finalize how close the radar should lock onto them though. But sometimes you will get a clean lock just by radar (which from manual also can be done).

On the opposite note. There is now notching possible. So you can hide in ground clutter if you fly perpendicular to the F16 with some luck.

**STT vs. SAM locks**
This is some AI traffic.
![image](https://user-images.githubusercontent.com/3764194/146895402-b7234ea6-05dd-431d-8f71-1f3da3eb56d2.png)

This mode you enter from RWS when locking something up (once). Its called RWS-SAM. It will show your lock but also search targets around it. Note that it will still only say RWS, not RWS-SAM, you have recognize that its in SAM mode by the fact that a target is circled.

If you lock the lock up once more you get into STT mode, where the radar will super focus only on the target. (AIM-7 needs that). (AIM-120 just need the SAM lock)

STT = Single Target Track
SAM = Situation Awareness Mode 

TWS mode, the one with circle around is the target that the missile will go after:
![image](https://user-images.githubusercontent.com/3764194/146895444-fc324f2f-8a52-46ae-82bd-84e228c3b2d6.png)


It can track up to 10 like that.
The one at the left is seen because the radar beam has some degrees coverage itself so can track a couple of degrees outside the boundaries.
So beside showing heading, this is very similar to RWS-SAM mode.

**BLEPS**
White when the radar hit return comes in, then it fades to black.
On the CNTL page you can set how many history bleps of that kind it should show.
![image](https://user-images.githubusercontent.com/3764194/146895522-c8fc6692-bfef-43ab-b665-50361afa858f.png)

Key `y` on the new radar is for TWS mode only. To switch between the 10 trackable targets.

**ACM modes**
In dogfight modes you have `CTRL-y`.  That deselects the target.
Lock is automatic in dogfight mode.

**Comment by NikolaiVChr** [comment]
**FAQ**

**Comment by NikolaiVChr** [comment]
Here you can see the ACM 60 coverage:

![image](https://user-images.githubusercontent.com/3764194/147045690-a58c499d-4a90-4692-846d-2799cacf0876.png)

**Comment by NikolaiVChr** [comment]
Development started in 2017 its now about ready for deployment.

Richards original design that started it all:
![image](https://user-images.githubusercontent.com/3764194/149751466-d60da908-4fa9-4bb2-a5b8-c641ff31a43b.png)


Sorta how the core of it ended up:
![image](https://user-images.githubusercontent.com/3764194/149751351-bc0c5456-c769-4add-93aa-6e8f6725675e.png)
