### ISSUE TITLE
DED CRUS Improvements

### ISSUE THREAD

**Issue by BobDotCom** [NikolaiVChr/f16#548]
Taken from #543

## Todo
- [ ] Rewrite the HUD cues to no longer depend on the HUD SVG. Not explicitly required before merging but requested by @NikolaiVChr.
- [ ] Add CRUS EDR and CRUS HOME
- [ ] Fix CRUS RNG to support any stpt
- [x] Fix the CRUS mode selection to use M-SEL button instead of enter button.
- [ ] Bind the airspeed cues to a min/max vertical position, the MLU m1 doesn't mention this but I think it would make sense.
