### ISSUE TITLE
Arms: AIM-9X improvements

### ISSUE THREAD

**Issue by BobDotCom** [NikolaiVChr/f16#555]
This issue will be a TO-DO list for planned improvements to the AIM-9X (List originally from #530).

# TODO (At some point)
- [x] Add 9X support to into damage code for other assets NikolaiVChr/OpRedFlag@7f16d2513ad239ceb01d27ea8787b3f932f4a044
  - [ ] Verify that all assets are updated with the new damage code
- [x] Fix launch sound 4a985cf96ce1748ab5ee3a53e9712041d35ea96b
- [ ] Improve Model
  The current one is overall OK, but an improved texture would be nice. The paintkit is available in the discord server: https://discord.com/channels/379782363061813248/496121096492417025/1108813739253313546
- [ ] Verify data is accurate
  - [ ] Find accurate cooling specs, since the 9X has a new cooling system.
  - [ ] Most fields that are estimated or unchanged from the 9M have in-code TODO messages, those should all be checked.
- [ ] Resolve all in-code TODO messages

**Comment by NikolaiVChr** [comment]
Also
- [ ] Part of the body is not round.
- [ ] Diameter check
- [ ] Tail proportions off
- [ ] Tip is too pointy

**Comment by BobDotCom** [comment]
> Also
> 
>     * [ ]  Part of the body is not round.
> 
>     * [ ]  Diameter check
> 
>     * [ ]  Tail proportions off
> 
>     * [ ]  Tip is too pointy

Added to the main list 👍

**Comment by NikolaiVChr** [comment]
Might be too OP for a block I, fcr-fov perhaps be reduced to +/- 90.
